In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min
from mpl_toolkits.mplot3d import Axes3D

In [2]:
#Se leen los datos del fichero
ciclistas = open ('/Users/34603/Desktop/TFG/Python/ciclistasVariablesSinNormalizarNiNombres.txt','r')
dataSet = list()
labels = list()

for linea in ciclistas: #Recorremos cada linea del archivo
    caracteristicas = linea.split()
    k=0
    for elemento in caracteristicas:
        if k==0:
            clase = 1 if caracteristicas[k] == "Profesional" else 0
            labels.append(clase)
            k=k+1
    variables=[float(elemento) for elemento in caracteristicas[1:]]
    dataSet.append(variables)
dataSet=np.array(dataSet) 
labels=np.array(labels)

num_variables=len(dataSet[1,:])
num_individuos=len(dataSet[:,1])

In [3]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos
#kmeans.cluster_centers_
print("Resultados sin normalizar:")
print("Etiquetas de KMeans")
print(output)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)


#Se normalizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

outputNormal = kmeans.fit(dataSetNormalizad).labels_ 
print("Resultados de KMeans al normalizar las variables:")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados sin normalizar:
Etiquetas de KMeans
[1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
3
Criterio de parada: 
568274.7332661266
Resultados de KMeans al normalizar las variables:
Etiquetas de KMeans
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
2
Criterio de parada: 
1157.6816186587807


In [37]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normalizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[3,4,5,6,7,18,24,34,39,40,41]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con las variables seleccionadas:")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con las variables seleccionadas:
Etiquetas de KMeans
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
3
Criterio de parada: 
94.82258234517076


In [4]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normalizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[4]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con Wingate Mean:")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con Wingate Mean:
Etiquetas de KMeans
[0 0 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
3
Criterio de parada: 
4.936773793216468


In [35]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normalizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[18,24,34,39,40,41]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con las variables seleccionadas fisiológicas:")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con las variables seleccionadas fisiológicas:
Etiquetas de KMeans
[1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
2
Criterio de parada: 
54.6582110718923


In [5]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normalizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[6]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con Power Mean:")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con Power Mean:
Etiquetas de KMeans
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
2
Criterio de parada: 
4.612650661633143


In [33]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normalizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[3]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con Wingate Peak:")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con Wingate Peak:
Etiquetas de KMeans
[0 0 0 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
3
Criterio de parada: 
5.318453096634752


In [32]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normaizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSet[:,[18]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con la variable Post 24h CK:")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con la variable Post 24h CK:
Etiquetas de KMeans
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
3
Criterio de parada: 
31743.16666666666


In [30]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normaizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[24]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con la variable CL 0':")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con la variable CL 0':
Etiquetas de KMeans
[1 0 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
4
Criterio de parada: 
5.046326997804486


In [29]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normalizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[34]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con la variable GLUC 0':")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con la variable GLUC 0':
Etiquetas de KMeans
[0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
2
Criterio de parada: 
7.1934399362088515


In [28]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normaizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[39]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con la variable Post SBP 0':")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con la variable Post SBP 0':
Etiquetas de KMeans
[0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 1 1 1 1]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
2
Criterio de parada: 
5.725248508946321


In [25]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normaizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[40]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con la variable Post DBP 0':")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con la variable Post DBP 0':
Etiquetas de KMeans
[1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
2
Criterio de parada: 
4.511934603807397


In [24]:
#Se crea el modelo KMeans
kmeans = KMeans(n_clusters=2,n_init=10000)
output = kmeans.fit(dataSet).labels_ #Este método realiza la división de nuestros datos

#Se normaizan las variables
mu=np.mean(dataSet,axis=0)
sigma=np.std(dataSet,axis=0)
dataSetNormalizad=((dataSet-mu)/sigma)

#Se seleccionan las variables más informadas
VariablesSelec=dataSetNormalizad[:,[41]]

outputNormal = kmeans.fit(VariablesSelec).labels_ 
print("Resultados de KMeans con la variable Post SBP 3':")
print("Etiquetas de KMeans")
print(outputNormal)
print("Etiquetas del dataSet")
print(labels)
print("Número de iteraciones ejecutadas")
print(kmeans.n_iter_)
print("Criterio de parada: ")
print(kmeans.inertia_)

Resultados de KMeans con la variable Post SBP 3':
Etiquetas de KMeans
[1 1 1 1 1 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
Etiquetas del dataSet
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
Número de iteraciones ejecutadas
2
Criterio de parada: 
5.542333663880627
